### ISSUE TITLE
Any reason the -m argument has been removed?

### ISSUE THREAD

**Issue by tvjon** [6by9/v4l2_mmal#1]
It would be useful to render via mmal too in this "simplified" version.

Thank you.

**Comment by 6by9** [comment]
There never has been a -m flag in this repo, although it is in the help text. There is no other option than to pass the data into MMAL.

It's been a while since I looked at this app, but it should send the V4L2 frames to the destinations listed in ```dests``` (https://github.com/6by9/v4l2_mmal/blob/master/v4l2_mmal.c#L62), and that includes video_render.

**Comment by 6by9** [comment]
As I had a suitable device hooked up I've just tried this.
It does render via MMAL as checked in. 
If you remove the commenting from the two lines at in ```dests``` then it will create either and H264 stream or stream of stills (BMP as checked in, but that drops frames. JPEG works fine). Filenames get slightly mangled as <stream>_<supplied filename>, so ```-E foo.h264``` ends up with 0_foo.h264 for the stream via video_encode, and 1_foo.h264 for the stream via image_encode (even though it's not an h264 stream).

The README and help text do need amending - they're still the old yavta texts.

**Comment by tvjon** [comment]
Sorry for delay, I've been out in the field.

"remove the commenting from the two lines at in dests "

I'm wondering if we're looking at the same file here.

https://github.com/6by9/v4l2_mmal/blob/master/v4l2_mmal.c

is what I'm working with.
Which lines are you referring to exactly please?

I've changed 
#define VCSM_IMPORT_DMABUF MMAL_TRUE
to 
#define VCSM_IMPORT_DMABUF MMAL_FALSE

along with
#define MMAL_ENCODING_UNUSED 1

I don't seem to see what you're seeing...

Thank you.

**Comment by 6by9** [comment]
Are you testing with a USB webcam again? As with yavta, I'd written this for the Unicam receiver that uses the dma_contig allocator. 

I had local diffs that I hadn't realised which switched to BMP and disabled some dests.

The ```VCSM_IMPORT_DMABUF``` define isn't used at all in this app. I guess I ought to check for errors on import and switch to VCHI copying the data. Things are pretty busy at the moment, but I'll see what I can do.

**Comment by tvjon** [comment]
Yes, I am. It's a third less lines to study in this file, & I'm interested to see what can be removed to get to a very basic working level.

I hadn't appreciated the different target you had in mind.

Ah, that explains the differences then.

I imagine you are, so I'll try not to pester, sorry..

**Comment by 6by9** [comment]
OK, a couple of patches pushed.

As noted in the commit text for 8c2f5990ca6c974aacdc1c9ae56a70ecfdb3df48, vcsm_import_dmabuf blows up in the kernel on an invalid buffer instead of returning an error for reasons I haven't yet investigated.
The simple diff of
```
@@ -649,7 +649,7 @@ static int video_alloc_buffers(struct device *dev, int nbufs)
                        if (!ioctl(dev->fd, VIDIOC_EXPBUF, &expbuf)) {
                                buffers[i].dma_fd = expbuf.fd;
 
-                               buffers[i].vcsm_handle = vcsm_import_dmabuf(expbuf.fd, "V4L2 buf");
+                               buffers[i].vcsm_handle = 0; //vcsm_import_dmabuf(expbuf.fd, "V4L2 buf");
                        }
                        else
                        {
```
to skip that step totally means it works with my USB webcam.

I've also fixed up the frame rate calcs so that it doesn't report almost all buffers as having been dropped.

**Comment by 6by9** [comment]
vcsm_import_dmabuf error found - it's actually in the error path.
PR up for the kernel fix on 4.19 (https://github.com/raspberrypi/linux/pull/2752) I'll sort a 4.14 PR in a moment.

**Comment by 6by9** [comment]
Both https://github.com/raspberrypi/linux/pull/2752 and https://github.com/raspberrypi/linux/pull/2753 are now merged. That fix will appear in an rpi-update kernel sometime soon. 

With that, v4l2_mmal seems to happily stream and encode from either Unicam (videobuf2_dma_contig and importable via dmabuf) or uvcvideo (videobuf2_vmalloc and not importable via dmabuf).

**Comment by tvjon** [comment]
You have indeed been busy!

I'll watch for the update, thank you.

Oh, one oddity I noticed today; according to the output you see below, camera found etc., yet the camera's red light remains OFF. Strange. I've just done a sanity check with the big version of your yavta, & it records a file ok, along with camera red light ON.

pi@sa1:v4l2_mmal-master-fix $ ./v4l2_mmal -c300 -n3  -Ej.264  /dev/video0

We're encoding to j.264
Device /dev/video0 opened.
Device `USB Camera-B4.09.24.1' on `usb-3f980000.usb-1.2' (driver 'ov534') is a video capture (without mplanes) device.
Video format: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400
Current frame rate: 30/1
vc.ril.isp:in:0(YUYV)(0xa67fb0)type: video, fourcc: YUYV bitrate: 0, framed: 0 extra data: 0, (nil) width: 640, height: 480, (0,0,640,480) pixel aspect ratio: 0/0, frame rate: 0/0 buffers num: 3(opt 1, min 1), size: 614400(opt 614400, min: 614400), align: 0Created pool of length 3, size 0
format->video.size now 640x480
Setup output port
Writing data to 0_j.264
Create pool of 3 buffers for vc.ril.video_encode
Create pool of 8 buffers for vc.ril.video_encode
Sent buffer 0xa6e8e8Sent buffer 0xa6eac0Sent buffer 0xa6ec98Sent buffer 0xa6ee70Sent buffer 0xa6f048Sent buffer 0xa6f220Sent buffer 0xa6f3f8Sent buffer 0xa6f5d0Enable vc.ril.video_encode....
Setup output port
Writing data to 1_j.264
Create pool of 3 buffers for vc.ril.image_encode
Create pool of 8 buffers for vc.ril.image_encode
Sent buffer 0xa74568Sent buffer 0xa74740Sent buffer 0xa74918Sent buffer 0xa74af0Sent buffer 0xa74cc8Sent buffer 0xa74ea0Sent buffer 0xa75078Sent buffer 0xa75250Enable vc.ril.image_encode....
Create pool of 3 buffers for vc.ril.video_render
Enable vc.ril.video_render....
Create pool of 3 buffers of size 460800 for encode/render
3 buffers requested.
length: 614400 offset: 0 timestamp type/source: mono/EoF
Buffer 0/0 mapped at address 0x7140a000.

**Comment by tvjon** [comment]
Apart from now seeing the red light on the camera, still no joy I'm afraid...

$ vcgencmd version
Nov 15 2018 12:38:27 
Copyright (c) 2012 Broadcom
version ed5baf9520a3c4ca82ba38594b898f0c0446da66 (clean) (release)

$ uname -a
Linux sa1 4.19.2-v7+ #1162 SMP Thu Nov 15 12:28:05 GMT 2018 armv7l GNU/Linux


$ ./v4l2_mmal -c300 -n3   /dev/video0

Device /dev/video0 opened.
Device `USB Camera-B4.09.24.1' on `usb-3f980000.usb-1.3.1.3' (driver 'ov534') is a video capture (without mplanes) device.
Video format: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400
Current frame rate: 1/30
vc.ril.isp:in:0(YUYV)(0xddefb0)type: video, fourcc: YUYV bitrate: 0, framed: 0 extra data: 0, (nil) width: 640, height: 480, (0,0,640,480) pixel aspect ratio: 0/0, frame rate: 0/0 buffers num: 3(opt 1, min 1), size: 614400(opt 614400, min: 614400), align: 0Created pool of length 3, size 0
format->video.size now 640x480
Setup output port
Writing data to 0_file.h264
Create pool of 3 buffers for vc.ril.video_encode
Create pool of 8 buffers for vc.ril.video_encode
Sent buffer 0xde5cd8Sent buffer 0xde5eb0Sent buffer 0xde6088Sent buffer 0xde6260Sent buffer 0xde6438Sent buffer 0xde6610Sent buffer 0xde67e8Sent buffer 0xde69c0Enable vc.ril.video_encode....
Setup output port
Writing data to 1_file.h264
Create pool of 3 buffers for vc.ril.image_encode
Create pool of 8 buffers for vc.ril.image_encode
Sent buffer 0xdeb968Sent buffer 0xdebb40Sent buffer 0xdebd18Sent buffer 0xdebef0Sent buffer 0xdec0c8Sent buffer 0xdec2a0Sent buffer 0xdec478Sent buffer 0xdec650Enable vc.ril.image_encode....
Create pool of 3 buffers for vc.ril.video_render
Enable vc.ril.video_render....
Create pool of 3 buffers of size 460800 for encode/render
3 buffers requested.
length: 614400 offset: 0 timestamp type/source: mono/EoF
Buffer 0/0 mapped at address 0x71455000.
usrvcsm: [vcsm_import_dmabuf]: [1513] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Exported buffer 0 to dmabuf 10, vcsm handle 0
usrvcsm: [vcsm_vc_hdl_from_hdl]: [1513]: invalid device or handle!
Linking V4L2 buffer index 0 ptr 0xdf07e0 to MMAL header 0xde0fe0. mmal->data 0x0
length: 614400 offset: 614400 timestamp type/source: mono/EoF
Buffer 1/0 mapped at address 0x713bf000.
usrvcsm: [vcsm_import_dmabuf]: [1513] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Exported buffer 1 to dmabuf 11, vcsm handle 0
usrvcsm: [vcsm_vc_hdl_from_hdl]: [1513]: invalid device or handle!
Linking V4L2 buffer index 1 ptr 0xdf0850 to MMAL header 0xde11b8. mmal->data 0x0
length: 614400 offset: 1228800 timestamp type/source: mono/EoF
Buffer 2/0 mapped at address 0x71329000.
usrvcsm: [vcsm_import_dmabuf]: [1513] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Exported buffer 2 to dmabuf 12, vcsm handle 0
usrvcsm: [vcsm_vc_hdl_from_hdl]: [1513]: invalid device or handle!
Linking V4L2 buffer index 2 ptr 0xdf08c0 to MMAL header 0xde1390. mmal->data 0x0
0 (0) [-] none 0 614400 B 643.910890 643.910951 25.014 fps ts mono/EoF
mmal: mmal_port_send_buffer: vc.ril.isp:in:0(YUYV)(0xddefb0) received invalid buffer header
mmal_port_send_buffer failed 3
1 (1) [-] none 1 614400 B 643.944219 643.944277 30.004 fps ts mono/EoF
DROPPED FRAME - 0 and 33329, delta 33329
mmal: mmal_port_send_buffer: vc.ril.isp:in:0(YUYV)(0xddefb0) received invalid buffer header
mmal_port_send_buffer failed 3
2 (2) [-] none 2 614400 B 643.977489 643.977547 30.057 fps ts mono/EoF
DROPPED FRAME - 33329 and 66599, delta 33270
mmal: mmal_port_send_buffer: vc.ril.isp:in:0(YUYV)(0xddefb0) received invalid buffer header
mmal_port_send_buffer failed 3

**Comment by 6by9** [comment]
Something a little curious there. I've run it with a UVC camera:
```
pi@raspberrypi:~/v4l2_mmal $ ./v4l2_mmal -n3 /dev/video1 -c10
Device /dev/video1 opened.
Device `UVC Camera (046d:0825)' on `usb-3f980000.usb-1.3' (driver 'uvcvideo') is a video capture (without mplanes) device.
Video format: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400
Current frame rate: 30/1
vc.ril.isp:in:0(YUYV)(0x75ffb0)type: video, fourcc: YUYV bitrate: 0, framed: 0 extra data: 0, (nil) width: 640, height: 480, (0,0,640,480) pixel aspect ratio: 0/0, frame rate: 0/0 buffers num: 3(opt 1, min 1), size: 614400(opt 614400, min: 614400), align: 0Created pool of length 3, size 0
format->video.size now 640x480
Setup output port
Writing data to 0_file.h264
Create pool of 3 buffers for vc.ril.video_encode
Create pool of 8 buffers for vc.ril.video_encode
Sent buffer 0x7668e8Sent buffer 0x766ac0Sent buffer 0x766c98Sent buffer 0x766e70Sent buffer 0x767048Sent buffer 0x767220Sent buffer 0x7673f8Sent buffer 0x7675d0Enable vc.ril.video_encode....
Setup output port
Writing data to 1_file.h264
Create pool of 3 buffers for vc.ril.image_encode
Create pool of 8 buffers for vc.ril.image_encode
Sent buffer 0x76c568Sent buffer 0x76c740Sent buffer 0x76c918Sent buffer 0x76caf0Sent buffer 0x76ccc8Sent buffer 0x76cea0Sent buffer 0x76d078Sent buffer 0x76d250Enable vc.ril.image_encode....
Create pool of 3 buffers for vc.ril.video_render
Enable vc.ril.video_render....
Create pool of 3 buffers of size 460800 for encode/render
3 buffers requested.
length: 614400 offset: 0 timestamp type/source: mono/SoE
Buffer 0/0 mapped at address 0x7140a000.
usrvcsm: [vcsm_import_dmabuf]: [7459] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Linking V4L2 buffer index 0 ptr 0x7713e8 to MMAL header 0x761fe0. mmal->data 0x7140A000
length: 614400 offset: 614400 timestamp type/source: mono/SoE
Buffer 1/0 mapped at address 0x71374000.
usrvcsm: [vcsm_import_dmabuf]: [7459] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Linking V4L2 buffer index 1 ptr 0x771458 to MMAL header 0x7621b8. mmal->data 0x71374000
length: 614400 offset: 1228800 timestamp type/source: mono/SoE
Buffer 2/0 mapped at address 0x712de000.
usrvcsm: [vcsm_import_dmabuf]: [7459] [V4L2 buf]: ioctl mem-import-dmabuf FAILED [-1] (hdl: 0)
Linking V4L2 buffer index 2 ptr 0x7714c8 to MMAL header 0x762390. mmal->data 0x712DE000
0 (0) [-] none 0 614400 B 59261.763270 59263.487540 192.678 fps ts mono/SoE
1 (1) [-] none 1 614400 B 59263.487522 59263.519763 0.580 fps ts mono/SoE
DROPPED FRAME - 0 and 1724252, delta 1724252
2 (2) [-] none 2 614400 B 59263.519739 59263.555427 31.040 fps ts mono/SoE
3 (0) [-] none 3 614400 B 59263.555405 59263.587638 28.038 fps ts mono/SoE
4 (1) [-] none 4 614400 B 59263.587622 59263.623304 31.040 fps ts mono/SoE
5 (2) [-] none 5 614400 B 59263.623283 59263.655516 28.042 fps ts mono/SoE
6 (0) [-] none 6 614400 B 59263.655494 59263.687745 31.045 fps ts mono/SoE
7 (1) [-] none 7 614400 B 59263.687721 59263.723401 31.030 fps ts mono/SoE
8 (2) [-] none 8 614400 B 59263.723381 59263.755618 28.043 fps ts mono/SoE
9 (0) [-] none 9 614400 B 59263.755593 59263.791282 31.044 fps ts mono/SoE
Captured 10 frames in 2.033202 seconds (4.918349 fps, 3021833.401450 B/s).
Total number of frames dropped 1
Closing dma_buf 10
Closing dma_buf 11
Closing dma_buf 12
3 buffers released.
Failed to find matching V4L2 buffer for mmal buffer 0x761fe0
pi@raspberrypi:~/v4l2_mmal $ 
```
Note no
```usrvcsm: [vcsm_vc_hdl_from_hdl]: [1513]: invalid device or handle!```
lines. If ```vcsm_import_dmabuf``` has failed then I'd expect ```buffers[i].vcsm_handle``` to be 0, so no call to ```vcsm_vc_hdl_from_hdl``` at line 664.
Can you do a quick debug with GDB (or extra logging) to confirm the value of ```buffers[i].vcsm_handle```?

**Comment by 6by9** [comment]
Hang on, you had noticed that there was an update to this repo as well as the one to the kernel?

https://github.com/6by9/v4l2_mmal/issues/1#issuecomment-438619914
> OK, a couple of patches pushed.

Prior to that I would expect the log output that you see.

**Comment by tvjon** [comment]
"you had noticed that there was an update to this repo as well as the one to the kernel?"

Yes, I had, but it helps when having several copies in use to choose the latest download...

Picked the right one & now ok.
Your yavta fork surprisingly (to me) registers about 27% cpu usage. 

V4l2_mmal about 21 %.

My primitive mickey-mouse omx version (still needing an ARM integer 422to420 conversion) averages 3%. That's just outputting to a dispmanx layer, no h264 yet.

So I'be interested to see where those cycles are going to in this current app.

Anyway  I can now press on. Sorry to trouble you.

**Comment by 6by9** [comment]
Ouch, I wasn't expecting the CPU usage to be that high, but I see the same thing too (even after asking for 5fps).
The ```select``` obviously isn't doing what it's meant to. I'll have a quick look.

**Comment by 6by9** [comment]
Ah yes, it helps if you don't leave uninitialised values lying around.
Not setting the write fds and not then passing in NULL to select doesn't help.

Fix that (commit made) and I'm around the 4% mark according to htop. I'm guessing the same is true in yavta.

**Comment by 6by9** [comment]
OK, and these changes have now been ported across to my yavta fork too, so it will work with most other webcams automagically.
I wasn't seeing high CPU load, but that's presumably dependent on just the uninitialised variables of the ```fds``` array, and I was getting lucky.

**Comment by 6by9** [comment]
Happy to close?

**Comment by tvjon** [comment]
Cpu load is now reduced, though still about 14 % here, but rendering & file creation are now ok, so yes, I'll close it thank you.
