### ISSUE TITLE
ADV7280A-M ACE Control

### ISSUE THREAD

**Issue by danriches** [6by9/v4l2_mmal#2]
Hiya,

In messing around with this and the ADV7280A-M chip, I've discovered that the chip can sometimes increase or decrease the default contrast ratio. This was experienced between power cycling so my question is how would I enable / disable ACE as seen on bottom of page 18 of the ADV7280A-M datasheet? Especially as the GPU has exclusive access to the i2c bus? I can't see anything concrete in the driver so I'm assuming it's at some default but I can't seem to find out where this is? Can some ioctl call be used to get the driver to issue the enable / disable command?

Sorry this isn't exactly the place for this but couldn't think of how else to ask you. Many thanks for any info or pointers you may have,

Dan

**Comment by 6by9** [comment]
> Especially as the GPU has exclusive access to the i2c bus?

The GPU doesn't touch the ADV728x as it has no driver for it. The Linux kernel driver is responsible for all control of the device. (The GPU only takes over i2c-0 when using raspivid/raspistill for the standard Pi camera modules).

The [kernel driver](https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/media/i2c/adv7180.c#L144)  does have defines for registers ADV7180_REG_ACE_CTRL1 and ADV7180_REG_ACE_CTRL5, but never references them.
My datasheet for the ADV7282 claims that ADV7180_REG_ACE_CTRL1 defaults to 0 to disable ACE. If you think that isn't the case, then you could insert a call in the driver along the lines of 
```
ret = adv7180_write(state, ADV7180_REG_ACE_CTRL1, 0);
```
to ensure that it is disabled. Or perhaps read it back via ```adv7180_read``` to esnure it is off.

Some drivers implement the g_register and s_register operations if CONFIG_VIDEO_ADV_DEBUG is set. Ioctls VIDIOC_DBG_S_REGISTER and VIDIOC_DBG_G_REGISTER then allow userspace to poke registers directly. adv7180 isn't one of them, although it could be added.

**Comment by danriches** [comment]
I found the ACE set to default as off moments after posting, typical me ;) I think for the moment I'll change the fast switching to turn on / off ACE and see what happens, if this cures my problem I'll implement it properly and merge the changes after checking this is ok. Thanks for getting back to me it's greatly appreciated!!

Kind Regards, Dan

**Comment by danriches** [comment]
I'm having a senior moment I think, if i2cdetect shows UU under the address 0x40 & 0x44 then that means the driver is using it and I can't issue any writes to it can I? So other than manually writing the registers myself without the driver loaded means adapting the driver to support the writes I need doesn't it?

Sorry to be a pain! Kind Regards,

Dan

**Comment by 6by9** [comment]
You want I2C_SLAVE_FORCE to allow you to select an I2C slave even if there is a kernel driver bound to it.
