### ISSUE TITLE
Compiling under g++ gives errors

### ISSUE THREAD

**Issue by danriches** [6by9/v4l2_mmal#3]
Hiya,

Sorry to be a pain but I'm trying to compile this under g++ so I get c++ compilation as I'm using an OpenCV library for conversion and subsequent processing. I get the following errors which I'm not sure how to correct:
`
sudo make
g++ -Iinclude -I/opt/vc/include -pipe -W -Wall -Wextra -g -O0 -I/usr/local/include/opencv4 -c -o v4l2_mmal_HDMI.o v4l2_mmal_HDMI.c
v4l2_mmal_HDMI.c:76:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 };
 ^
v4l2_mmal_HDMI.c:76:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
v4l2_mmal_HDMI.c:76:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
v4l2_mmal_HDMI.c: In function ‘int video_alloc_buffers(device*, int)’:
v4l2_mmal_HDMI.c:612:18: error: invalid conversion from ‘void*’ to ‘buffer*’ [-fpermissive]
  buffers = malloc(rb.count * sizeof buffers[0]);
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
v4l2_mmal_HDMI.c:662:70: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     buffers[i].vcsm_handle = vcsm_import_dmabuf(expbuf.fd, "V4L2 buf");
                                                                      ^
v4l2_mmal_HDMI.c:679:38: error: invalid conversion from ‘void*’ to ‘uint8_t* {aka unsigned char*}’ [-fpermissive]
     mmal_buf->data = buffers[i].mem[0]; //Only deal with the single planar API
                      ~~~~~~~~~~~~~~~~^
v4l2_mmal_HDMI.c: In function ‘int setup_mmal(device*, int, const char*)’:
v4l2_mmal_HDMI.c:1138:45: error: invalid conversion from ‘__u32 {aka unsigned int}’ to ‘v4l2_field’ [-fpermissive]
          fmt.fmt.pix.sizeimage, fmt.fmt.pix.field, fmt.fmt.pix.flags) < 0)
                                 ~~~~~~~~~~~~^~~~~
v4l2_mmal_HDMI.c:475:12: note:   initializing argument 7 of ‘int video_set_format(device*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, v4l2_field, unsigned int)’
 static int video_set_format(struct device *dev, unsigned int w, unsigned int h,
            ^~~~~~~~~~~~~~~~
v4l2_mmal_HDMI.c:1191:10: error: no match for ‘operator+=’ (operand types are ‘MMAL_STATUS_T’ and ‘MMAL_STATUS_T’)
   status += mmal_port_parameter_set_boolean(ip, MMAL_PARAMETER_ZERO_COPY, MMAL_TRUE);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
v4l2_mmal_HDMI.c:1300:33: error: invalid conversion from ‘void*’ to ‘FILE* {aka _IO_FILE*}’ [-fpermissive]
     dev->components[i].pts_fd = (void*)fopen(tmp_filename, "wb");
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
v4l2_mmal_HDMI.c: In function ‘void video_save_image(device*, v4l2_buffer*, const char*, unsigned int)’:
v4l2_mmal_HDMI.c:1448:19: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
  filename = malloc(size + 12);
             ~~~~~~^~~~~~~~~~~
v4l2_mmal_HDMI.c: In function ‘int video_do_capture(device*, unsigned int, unsigned int, const char*, int, int)’:
v4l2_mmal_HDMI.c:1590:25: error: invalid conversion from ‘__u32 {aka unsigned int}’ to ‘v4l2_field’ [-fpermissive]
     v4l2_field_name(buf.field),
`

Any ideas or pointers would be greatly appreciated.

Cheers,

Dan

**Comment by 6by9** [comment]
You should be able to mix and match C and C++ source files, but that's a different question.

C++ files would normally have the extension cpp.

Yes, there are a couple of dodgy or missing casts in there, but also C++ is far fussier about types, with things like addition of enums not being permitted.

New branch pushed called Cplusplus that has those fixed up. This is only a hacked together test program, and intended to be C, so I'm not proposing merging it back into master.

**Comment by danriches** [comment]
You're a god send, thank you ever so much!! That would have taken me who knows how long to adjust. Can I send you a bottle of something as a thank you? Sadly have no loo roll which seems to be todays form of cash lol!!

Kind Regards,

Dan
